### PR TITLE
test(coalescing-manager): implemented coalescing-manager tests

### PR DESCRIPTION
**Pull request by hoebbelsB**
implemented missing coalescing-manager tests in regards of #202 

image

### CODE REVIEW

**Comment by BioPhoton** [comment]
I guess we can remove the default [here](https://github.com/BioPhoton/rx-angular/blob/master/libs/template/src/lib/core/utils/coalescing-manager.ts#L39) as they make no sense...

**Comment by hoebbelsB** [comment]
> I guess we can remove the default [here](https://github.com/BioPhoton/rx-angular/blob/master/libs/template/src/lib/core/utils/coalescing-manager.ts#L39) as they make no sense...

exactly what I was thinking

**Comment by BioPhoton** [comment]
Let me know when you are done!

**Comment by hoebbelsB** [comment]
> Let me know when you are done!

@BioPhoton done

**Pull request merged**
