### PR TITLE
Feature: jsdocs to md automation

### PR DESCRIPTION
**Pull request by hoebbelsB**
Copied [scripts!](https://github.com/vendure-ecommerce/vendure/tree/master/docs) from @michaelbromley and adapted them according to our needs. 

The command `generate-typescript-docs` parses all configured (currently only state lib) folders for correctly formatted jsDoc and translates them to markdown.

 ```bash
yarn generate-typescript-docs [-w]
```
There is a [README](https://github.com/BioPhoton/rx-angular/tree/jsdocs-to-md-automation/tools/scripts/docs) explaining exactly what happens.

I have also added correct JSDoc (including examples + description) to all functions of the `RxState`. You find the [markdown version of this here.](https://github.com/BioPhoton/rx-angular/blob/jsdocs-to-md-automation/apps/docs/generated/state/_index.md).

This issue refers to #17 due to the JSDoc part. But this is actually the basis for creating a doc app.

### CODE REVIEW

**Comment by BioPhoton** [comment]
Hi! Thank a LOT for this PR!

Could you put a .gitignore into the generated folder and remove the generated files from the PR, please? As they are generated we don'T put them into version control.

**Comment by michaelbromley** [comment]
😎

**Comment by hoebbelsB** [comment]
> Hi! Thank a LOT for this PR!
> 
> Could you put a .gitignore into the generated folder and remove the generated files from the PR, please? As they are generated we don'T put them into version control.

My original intention to include them was just to showcase the outcome without you having to check out and generate on your own. But when I'm thinking about it, we could leave them inside the repo since they will be used in the docs app anyway?

**Comment by BioPhoton** [comment]
Yes, we host them, but we should not keep generated stuff in the repo.

**Comment by michaelbromley** [comment]
Fwiw I do not check in the generated docs, I have a netlify integration so netlify will build and deploy whenever I push to the docs branch automatically.

**Pull request merged**
